{"uuid": "d3d6eb5b-d759-4dd9-8d55-7594aec39884", "children": ["fca934da-41fd-4098-8e31-82972028b7e2"], "befores": [{"name": "_xunit_setup_method_fixture_TestUserAuth", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizavetafilippova/PycharmProjects/LearnQA_Python_API/logs/log_2023-01-08_15-37-17.log'\n", "trace": "  File \"/Library/Python/3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Python/3.8/site-packages/_pytest/fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Python/3.8/site-packages/_pytest/fixtures.py\", line 900, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Library/Python/3.8/site-packages/_pytest/python.py\", line 907, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"/Library/Python/3.8/site-packages/_pytest/python.py\", line 788, in _call_with_optional_argument\n    func()\n  File \"/Users/elizavetafilippova/PycharmProjects/LearnQA_Python_API/tests/test_user_auth.py\", line 22, in setup\n    response1 = MyRequests.post(\"/user/login\", data=data)\n  File \"/Users/elizavetafilippova/PycharmProjects/LearnQA_Python_API/lib/my_requests.py\", line 17, in post\n    return MyRequests._send(url, data, headers, cookies, 'POST')\n  File \"/Users/elizavetafilippova/PycharmProjects/LearnQA_Python_API/lib/my_requests.py\", line 39, in _send\n    Logger.add_request(url, data, headers, cookies, method)\n  File \"/Users/elizavetafilippova/PycharmProjects/LearnQA_Python_API/lib/logger.py\", line 28, in add_request\n    cls._write_log_to_file(data_to_add)\n  File \"/Users/elizavetafilippova/PycharmProjects/LearnQA_Python_API/lib/logger.py\", line 12, in _write_log_to_file\n    with open(cls.file_name, 'a', encoding='utf-8') as logger_file:\n"}, "steps": [{"name": "POST request to URL '/user/login'", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/Users/elizavetafilippova/PycharmProjects/LearnQA_Python_API/logs/log_2023-01-08_15-37-17.log'\n", "trace": "  File \"/Users/elizavetafilippova/PycharmProjects/LearnQA_Python_API/lib/my_requests.py\", line 17, in post\n    return MyRequests._send(url, data, headers, cookies, 'POST')\n  File \"/Users/elizavetafilippova/PycharmProjects/LearnQA_Python_API/lib/my_requests.py\", line 39, in _send\n    Logger.add_request(url, data, headers, cookies, method)\n  File \"/Users/elizavetafilippova/PycharmProjects/LearnQA_Python_API/lib/logger.py\", line 28, in add_request\n    cls._write_log_to_file(data_to_add)\n  File \"/Users/elizavetafilippova/PycharmProjects/LearnQA_Python_API/lib/logger.py\", line 12, in _write_log_to_file\n    with open(cls.file_name, 'a', encoding='utf-8') as logger_file:\n"}, "start": 1673177837791, "stop": 1673177837791}], "start": 1673177837791, "stop": 1673177837796}], "start": 1673177837791, "stop": 1673177837850}